### PR TITLE
Update htop.sh

### PR DESCRIPTION
**Pull request by Nivigor**
Updated for XigmaNAS 12.*, not need exact file names

### CODE REVIEW

**Comment by Nivigor** [comment]
Script independent to Xigmanas version

**Comment by Nivigor** [comment]
Script independent to Xigmanas version

**Comment by Nivigor** [comment]
Script independent to Xigmanas version

**Comment by ginggs** [comment]
Implemented in 28bd31e4923afcb2247ef39612058f82d9a796e6

**Pull request closed without merging**
